# Online Model Variables
ONLINE_MODEL_RUN_DATE = '18072022'
ONLINE_MODEL_NAME = 'catboost_model'
LOCAL_ONLINE_MODEL_SAVE_PATH = f'/home/ec2-user/SageMaker/ml-demand-forecasting/temp/model_saves/online/{ONLINE_MODEL_RUN_DATE}/model_online_{ONLINE_MODEL_RUN_DATE}/{ONLINE_MODEL_NAME}'
S3_ONLINE_MODEL_SAVE_PATH = f'data_science/dfm/online_clothing_v2/18072022/model_online_{ONLINE_MODEL_RUN_DATE}/{ONLINE_MODEL_NAME}'
S3_ONLINE_DATA_FILE_PATH = f's3://hal-bi-bucket/data_science/dfm/online_clothing_v2/{ONLINE_MODEL_RUN_DATE}/master_join_online.parquet'

FEATURES_ONLINE = [
    'original_price_usd',
    'first_week_of_month',
    'product_cost_usd',
    'is_lookbook_collection',
    'year',
    'warehouse',
    'last_week_of_month',
    'is_mega_campaign_order',
    'is_big_collection',
    'released_month',
    'week_id',
    'sub_product_line',
    'henry_category_1',
    'henry_category_2',
    'henry_category_3',
    'simple_color',
    'color',
    'fabric_custom_name',
    'hscode_id_fabric_name',
    'size',
    'style',
    'sleeve',
    'pattern',
    'sleevestyle',
    'neckline',
    'shape',
    'rise',
    'feature_item_discount_mean',
    'feature_item_discount_max',
    'feature_item_discount_std',
    'feature_voucher_discount_mean',
    'feature_voucher_discount_max',
    'feature_voucher_discount_std',
    'feature_discount_utilization_mean',
    'feature_discount_utilization_max',
    'feature_discount_utilization_std',
    'feature_dist_lookbook_mean',
    'feature_dist_lookbook_max',
    'feature_dist_lookbook_std',
    'feature_sales_grp1_mean',
    'feature_sales_grp1_max',
    'feature_sales_grp1_std',
    'feature_sales_grp2_mean',
    'feature_sales_grp2_max',
    'feature_sales_grp2_std',
    'feature_sales_grp3_mean',
    'feature_sales_grp3_max',
    'feature_sales_grp3_std',
    'size_dist',
    'week_dist',
    'avg_price_per_category',
    'price_ratio_category',
    'feature_price_cannibalization',
    'styles_in_collection'
]

CATEGORICAL_FEATURES_ONLINE = [
    'size',
    'warehouse',
    'released_month',
    'sub_product_line',
    'henry_category_1',
    'henry_category_2',
    'henry_category_3',
    'simple_color',
    'color',
    'fabric_custom_name',
    'hscode_id_fabric_name',
    'is_mega_campaign_order',
    'pattern',
    'sleevestyle',
    'neckline',
    'shape',
    'rise',
    'sleeve',
    'style', 
    'week_id',
    'first_week_of_month',
    'last_week_of_month',
    'is_lookbook_collection',
    'is_big_collection'
]


# Offline Model Variables
OFFLINE_MODEL_RUN_DATE = '11082022'
MODEL_NAME_OFFLINE = 'offline_model_catboost'
LOCAL_OFFLINE_MODEL_SAVE_PATH = f'/home/ec2-user/SageMaker/ml-demand-forecasting/temp/model_saves/offline/{OFFLINE_MODEL_RUN_DATE}/model_offline_11082022/offline_model_catboost'
S3_OFFLINE_MODEL_SAVE_PATH = f'data_science/dfm/offline_clothing_v2/{OFFLINE_MODEL_RUN_DATE}/model_offline_11082022/offline_model_catboost'
S3_OFFLINE_DATA_FILE_PATH = f's3://hal-bi-bucket/data_science/dfm/offline_clothing_v2/{OFFLINE_MODEL_RUN_DATE}/master_join_offline.parquet'

FEATURES_OFFLINE = [
    'product_cost_usd',
    'original_price_usd',
    'size', 
    'product_line',
    'sub_product_line',
    'henry_category_1',
    'henry_category_2', 
    'henry_category_3',
    'simple_color',
    'color',
    'fabric_custom_name',
    'hscode_id_fabric_name',
    'giveaway',
    'cluster',
    'pattern',
    'sleevestyle',
    'neckline',
    'shape',
    'rise',
    'sleeve',
    'style', 
    'week_id',
    'id_shop_name',
    'first_week_of_month',
    'last_week_of_month',
    'is_mega_campaign_order', 
    'avg_price_per_category',
    'price_ratio_category',
    'feature_price_cannibalization',
    'feature_item_discount_mean',
    'feature_item_discount_max',
    'feature_item_discount_std',
    'feature_voucher_discount_mean',
    'feature_voucher_discount_max',
    'feature_voucher_discount_std',
    'feature_discount_utilization_mean',
    'feature_discount_utilization_max',
    'feature_discount_utilization_std',
    'feature_traffic_dist_mean',
    'feature_traffic_dist_max',
    'feature_traffic_dist_std',
    'feature_retail_mkt_spend_dist_mean',
    'feature_retail_mkt_spend_dist_max',
    'feature_retail_mkt_spend_dist_std',
    'feature_sales_cat_mean',
    'feature_sales_cat_max',
    'feature_sales_cat_std',
    'feature_sales_cat2_mean',
    'feature_sales_cat2_max',
    'feature_sales_cat2_std',
    'feature_sales_cluster_mean',
    'feature_sales_cluster_max',
    'feature_sales_cluster_std',
    'feature_size_dist',
    'week_dist',
    'styles_in_collection'
]

CATEGORICAL_FEATURES_OFFLINE = [
    'size',
    'product_line',
    'sub_product_line',
    'henry_category_1',
    'henry_category_2',
    'henry_category_3',
    'simple_color',
    'color',
    'fabric_custom_name',
    'hscode_id_fabric_name',
    'is_mega_campaign_order',
    'cluster',
    'pattern',
    'sleevestyle',
    'neckline',
    'shape',
    'rise',
    'sleeve',
    'style', 
    'week_id',
    'id_shop_name',
    'first_week_of_month',
    'last_week_of_month',
    'giveaway'
]
